apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress        # typo fix: ngnix â†’ nginx
  namespace: test
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: test.sujeetkushwaha.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service   # make sure service name matches
            port:
              number: 80
