apiVersion: v1
kind: Service
metadata:
  name: test-server
  namespace: test
spec:
  ports:
    - protocol: TCP
      port: 80        # HTTP port
      targetPort: 80  # pod container port
  type: ClusterIP
